name: Nondex CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Build project with Maven
        run: mvn -B clean install -DskipTests -pl core -am
      - name: Test without Nondex
        run: mvn -pl core test
      - name: Test with Nondex
        run: mvn -pl core test edu.illinois:nondex-maven-plugin:2.1.1:nondex